/camera_node:
  ros__parameters:
    camera_name: narrow_stereo
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    frame_id: "camera_optical_frame"

    exposure_time: 3000
    gain: 0.0

    offset_x: 0
    offset_y: 0

/armor_detector:
  ros__parameters:
    debug: true

    detect_color: 0
    binary_thres: 80

    light.min_ratio: 0.08
    armor.min_light_ratio: 0.7

    classifier_threshold: 0.8
    ignore_classes: ["negative"]

/armor_tracker:
  ros__parameters:
    target_frame: odom

    ekf:
      sigma2_q_xyz: 5e-2
      sigma2_q_yaw: 1e1
      sigma2_q_r: 80.0

      r_xyz_factor: 2e-4
      r_yaw: 5e-3

    tracker:
      max_match_distance: 0.15
      tracking_thres: 3
      lost_time_thres: 0.6
